### ISSUE TITLE
Non of the test pages is playing.

### ISSUE THREAD

**Issue by 592da** [Manbearpixel/video-js-vpaid#1]
this should already work ?
here is a test vpaid tag :
http://ad3.liverail.com/?LR_PUBLISHER_ID=1331&LR_CAMPAIGN_ID=229&LR_SCHEMA=vast2-vpaid

Thanks

**Comment by Vuuo** [comment]
+1

**Comment by Manbearpixel** [comment]
@592da @Vuuo 
Hey sorry about the lateness of my response, I turned debug on and ran your URL and it seems when the URL is called from Flash using URLRequest, it does not find any SWF file. Instead it finds a variety of  MP4, WEBM, and FLV files. Yet surprisingly when I open the URL on a browser I see an SWF file show up. So I'm not sure if that liverail link is specifically targeting based on the origin of the request. I'll look into it as much as I can, but that is what I have found.

**Comment by Manbearpixel** [comment]
@592da @Vuuo 
Totally forgot I am no longer supporting this Repo, if you need VPAID support for your VideoJS player please take a look at my [VideoJS VPAID Plugin](https://github.com/Manbearpixel/videojs-vpaid) where I actively add new features and offer better support. Since it is a plugin it works on top of whatever configuration you are using. Thanks!
